spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: serviceBooks
        uri: lb://service-Books
        predicates:
        - Path=/books/**
        filters:
        - RewritePath=/books/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-books
            fallbackUri: forward:/fallback/serviceBooks
      - id: service-kitchen
        uri: lb://service-kitchen
        predicates:
        - Path=/kitchen/**
        filters:
        - RewritePath=/kitchen/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-kitchen
            fallbackUri: forward:/fallback/service-kitchen
      - id: service-customers
        uri: lb://service-customers
        predicates:
        - Path=/customers/**
        filters:
        - RewritePath=/customers/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-customers
            fallbackUri: forward:/fallback/serviceB  
      - id: ServiceWeather
        uri: lb://service-Weather
        predicates:
        - Path=/weather/**
        filters:
        - RewritePath=/weather/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-weather
            fallbackUri: forward:/fallback/serviceWeather  
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
